import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/theme/app_theme.dart';
import '../../domain/models/app_models.dart';
import '../providers/app_providers.dart';
import '../widgets/app_shell.dart';

class NudgeCenterScreen extends ConsumerWidget {
  const NudgeCenterScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(appStateProvider);
    final controller = ref.read(appStateProvider.notifier);
    final nudges = state.nudges.where((item) => !item.dismissed).toList();

    return SingleChildScrollView(
      padding: const EdgeInsets.fromLTRB(18, 12, 18, 18),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          TextButton.icon(
            onPressed: () => controller.setTab(0),
            icon: const Icon(Icons.arrow_back_rounded, size: 16, color: AppColors.muted),
            label: const Text('Back', style: TextStyle(color: AppColors.muted)),
          ),
          const Text(
            'Nudges',
            style: TextStyle(fontSize: 28, fontWeight: FontWeight.w900),
          ),
          const SizedBox(height: 6),
          Text(
            nudges.isEmpty
                ? 'No active nudges right now.'
                : '${nudges.length} active recommendation${nudges.length == 1 ? '' : 's'} from the orchestrator',
            style: const TextStyle(color: AppColors.muted, fontSize: 12),
          ),
          const SizedBox(height: 18),
          GlassCard(
            strong: true,
            radius: 28,
            child: const Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                AppSectionTitle(
                  'Event pipeline',
                  trailing: Text(
                    'Notification flow',
                    style: TextStyle(fontSize: 10, color: AppColors.muted),
                  ),
                ),
                SizedBox(height: 12),
                Text(
                  'Transactions trigger analysis, nudges are generated by the orchestrator, and this screen surfaces the resulting interventions in real time.',
                  style: TextStyle(fontSize: 12, color: AppColors.muted, height: 1.45),
                ),
              ],
            ),
          ),
          const SizedBox(height: 18),
          if (nudges.isEmpty)
            GlassCard(
              strong: true,
              radius: 28,
              child: const Text(
                'You are all caught up. ThinkTwice will notify you when a new intervention is worth acting on.',
                style: TextStyle(fontSize: 13, color: AppColors.muted, height: 1.45),
              ),
            )
          else
            for (var i = 0; i < nudges.length; i++) ...[
              _NudgeCard(
                nudge: nudges[i],
                onPrimary: () {
                  controller.completePrimaryNudgeAction(i);
                  if (nudges[i].primaryActionLabel.contains('Radar')) {
                    controller.setTab(2);
                  }
                },
                onSecondary: () {
                  if (nudges[i].secondaryActionLabel.contains('cheaper')) {
                    controller.setTab(2);
                    return;
                  }
                  controller.dismissNudge(i);
                },
              ),
              const SizedBox(height: 12),
            ],
        ],
      ),
    );
  }
}

class _NudgeCard extends StatelessWidget {
  const _NudgeCard({
    required this.nudge,
    required this.onPrimary,
    required this.onSecondary,
  });

  final NudgeModel nudge;
  final VoidCallback onPrimary;
  final VoidCallback onSecondary;

  @override
  Widget build(BuildContext context) {
    final riskColor = switch (nudge.riskLevel) {
      'High' => AppColors.risk,
      'Medium' => AppColors.gold,
      _ => AppColors.ai,
    };

    return GlassCard(
      strong: true,
      radius: 28,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                decoration: BoxDecoration(
                  color: riskColor.withValues(alpha: 0.15),
                  borderRadius: BorderRadius.circular(99),
                ),
                child: Text(
                  '${nudge.riskLevel} risk',
                  style: TextStyle(fontSize: 10, fontWeight: FontWeight.w800, color: riskColor),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Text(
            nudge.title,
            style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w800),
          ),
          const SizedBox(height: 8),
          Text(
            nudge.message,
            style: const TextStyle(fontSize: 13, color: AppColors.muted, height: 1.45),
          ),
          const SizedBox(height: 12),
          Text(
            nudge.impactLabel,
            style: const TextStyle(fontSize: 12, color: AppColors.ai, fontWeight: FontWeight.w700),
          ),
          const SizedBox(height: 14),
          Row(
            children: [
              Expanded(
                child: GradientButton(
                  label: nudge.primaryActionLabel,
                  gradient: AppColors.emeraldGradient,
                  onTap: onPrimary,
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          InkWell(
            onTap: onSecondary,
            borderRadius: BorderRadius.circular(20),
            child: GlassCard(
              strong: true,
              radius: 20,
              padding: const EdgeInsets.symmetric(vertical: 14),
              child: Center(
                child: Text(
                  nudge.secondaryActionLabel,
                  style: const TextStyle(fontWeight: FontWeight.w800),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
