/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as ResilienceRouteImport } from './routes/resilience'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NudgeRouteImport } from './routes/nudge'
import { Route as GxbankRouteImport } from './routes/gxbank'
import { Route as GamifyRouteImport } from './routes/gamify'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding.profile'
import { Route as OnboardingInitRouteImport } from './routes/onboarding.init'
import { Route as OnboardingBudgetRouteImport } from './routes/onboarding.budget'
import { Route as OnboardingAvatarRouteImport } from './routes/onboarding.avatar'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResilienceRoute = ResilienceRouteImport.update({
  id: '/resilience',
  path: '/resilience',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NudgeRoute = NudgeRouteImport.update({
  id: '/nudge',
  path: '/nudge',
  getParentRoute: () => rootRouteImport,
} as any)
const GxbankRoute = GxbankRouteImport.update({
  id: '/gxbank',
  path: '/gxbank',
  getParentRoute: () => rootRouteImport,
} as any)
const GamifyRoute = GamifyRouteImport.update({
  id: '/gamify',
  path: '/gamify',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/onboarding/profile',
  path: '/onboarding/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInitRoute = OnboardingInitRouteImport.update({
  id: '/onboarding/init',
  path: '/onboarding/init',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBudgetRoute = OnboardingBudgetRouteImport.update({
  id: '/onboarding/budget',
  path: '/onboarding/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAvatarRoute = OnboardingAvatarRouteImport.update({
  id: '/onboarding/avatar',
  path: '/onboarding/avatar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/gamify': typeof GamifyRoute
  '/gxbank': typeof GxbankRoute
  '/nudge': typeof NudgeRoute
  '/profile': typeof ProfileRoute
  '/radar': typeof RadarRoute
  '/resilience': typeof ResilienceRoute
  '/squad': typeof SquadRoute
  '/transactions': typeof TransactionsRoute
  '/welcome': typeof WelcomeRoute
  '/onboarding/avatar': typeof OnboardingAvatarRoute
  '/onboarding/budget': typeof OnboardingBudgetRoute
  '/onboarding/init': typeof OnboardingInitRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/gamify': typeof GamifyRoute
  '/gxbank': typeof GxbankRoute
  '/nudge': typeof NudgeRoute
  '/profile': typeof ProfileRoute
  '/radar': typeof RadarRoute
  '/resilience': typeof ResilienceRoute
  '/squad': typeof SquadRoute
  '/transactions': typeof TransactionsRoute
  '/welcome': typeof WelcomeRoute
  '/onboarding/avatar': typeof OnboardingAvatarRoute
  '/onboarding/budget': typeof OnboardingBudgetRoute
  '/onboarding/init': typeof OnboardingInitRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/gamify': typeof GamifyRoute
  '/gxbank': typeof GxbankRoute
  '/nudge': typeof NudgeRoute
  '/profile': typeof ProfileRoute
  '/radar': typeof RadarRoute
  '/resilience': typeof ResilienceRoute
  '/squad': typeof SquadRoute
  '/transactions': typeof TransactionsRoute
  '/welcome': typeof WelcomeRoute
  '/onboarding/avatar': typeof OnboardingAvatarRoute
  '/onboarding/budget': typeof OnboardingBudgetRoute
  '/onboarding/init': typeof OnboardingInitRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/coach'
    | '/dashboard'
    | '/gamify'
    | '/gxbank'
    | '/nudge'
    | '/profile'
    | '/radar'
    | '/resilience'
    | '/squad'
    | '/transactions'
    | '/welcome'
    | '/onboarding/avatar'
    | '/onboarding/budget'
    | '/onboarding/init'
    | '/onboarding/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/coach'
    | '/dashboard'
    | '/gamify'
    | '/gxbank'
    | '/nudge'
    | '/profile'
    | '/radar'
    | '/resilience'
    | '/squad'
    | '/transactions'
    | '/welcome'
    | '/onboarding/avatar'
    | '/onboarding/budget'
    | '/onboarding/init'
    | '/onboarding/profile'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/coach'
    | '/dashboard'
    | '/gamify'
    | '/gxbank'
    | '/nudge'
    | '/profile'
    | '/radar'
    | '/resilience'
    | '/squad'
    | '/transactions'
    | '/welcome'
    | '/onboarding/avatar'
    | '/onboarding/budget'
    | '/onboarding/init'
    | '/onboarding/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CoachRoute: typeof CoachRoute
  DashboardRoute: typeof DashboardRoute
  GamifyRoute: typeof GamifyRoute
  GxbankRoute: typeof GxbankRoute
  NudgeRoute: typeof NudgeRoute
  ProfileRoute: typeof ProfileRoute
  RadarRoute: typeof RadarRoute
  ResilienceRoute: typeof ResilienceRoute
  SquadRoute: typeof SquadRoute
  TransactionsRoute: typeof TransactionsRoute
  WelcomeRoute: typeof WelcomeRoute
  OnboardingAvatarRoute: typeof OnboardingAvatarRoute
  OnboardingBudgetRoute: typeof OnboardingBudgetRoute
  OnboardingInitRoute: typeof OnboardingInitRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resilience': {
      id: '/resilience'
      path: '/resilience'
      fullPath: '/resilience'
      preLoaderRoute: typeof ResilienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nudge': {
      id: '/nudge'
      path: '/nudge'
      fullPath: '/nudge'
      preLoaderRoute: typeof NudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gxbank': {
      id: '/gxbank'
      path: '/gxbank'
      fullPath: '/gxbank'
      preLoaderRoute: typeof GxbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamify': {
      id: '/gamify'
      path: '/gamify'
      fullPath: '/gamify'
      preLoaderRoute: typeof GamifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/init': {
      id: '/onboarding/init'
      path: '/onboarding/init'
      fullPath: '/onboarding/init'
      preLoaderRoute: typeof OnboardingInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/budget': {
      id: '/onboarding/budget'
      path: '/onboarding/budget'
      fullPath: '/onboarding/budget'
      preLoaderRoute: typeof OnboardingBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/avatar': {
      id: '/onboarding/avatar'
      path: '/onboarding/avatar'
      fullPath: '/onboarding/avatar'
      preLoaderRoute: typeof OnboardingAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CoachRoute: CoachRoute,
  DashboardRoute: DashboardRoute,
  GamifyRoute: GamifyRoute,
  GxbankRoute: GxbankRoute,
  NudgeRoute: NudgeRoute,
  ProfileRoute: ProfileRoute,
  RadarRoute: RadarRoute,
  ResilienceRoute: ResilienceRoute,
  SquadRoute: SquadRoute,
  TransactionsRoute: TransactionsRoute,
  WelcomeRoute: WelcomeRoute,
  OnboardingAvatarRoute: OnboardingAvatarRoute,
  OnboardingBudgetRoute: OnboardingBudgetRoute,
  OnboardingInitRoute: OnboardingInitRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
